### ISSUE TITLE
Why isn't this on the vscode marketplace?

### ISSUE THREAD

**Issue by miltoncandelero** [boocs/ue4-intellisense-fixes#1]
so... that.

Why do we install it by hand instead of uploading it?

https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by boocs** [comment]
1. Easier than going through the publishing process (laziness)
2. I just learned Typescript so using the Marketplace would seem too professional for a novice coder.

The one thing I can do is package it in a VSIX file and offer it as a download. I'll try to get that done soon.

**Comment by boocs** [comment]
I didn't realize you could host releases on github. Thanks for making me research. I've switched the installation instructions to use a VSIX file.

https://github.com/boocs/ue4-intellisense-fixes/releases/

Instructions on how to install on in the gist readme
https://gist.github.com/boocs/f63a4878156295b6e854cac68672f305

**Comment by miltoncandelero** [comment]
Good enough, not having to manually add files is waaaay better 👍
