### ISSUE TITLE
Local History Extension Compatibility

### ISSUE THREAD

**Issue by vladipus** [boocs/ue4-intellisense-fixes#32]
Hey, great extension you have here!

I'm having a small issue with the Local History extension which creates a `.history` folder inside of the project's root by default. Whenever I hit save, the new iteration is saved there and your extension is triggering a notification to ask to soft-reset the project. This is kind of annoying and I thought maybe you could ignore the `.history` folder from your change monitoring code or maybe even ignore all the `.*` folders and files.

Thanks!

**Comment by boocs** [comment]
Ok, i'll look what's up! Should be an easy fix.

**Comment by boocs** [comment]
This is the problem. Here's my glob for detecting a reset: "**/Source/\*\*/*.{h,hpp,hh,HPP,c,cpp,cc,CPP}"

Basically I bet in your .history folder there is a folder called Source. So if I remove the the '**/' part from the beginning, it should work and not trigger on Source folders in .history.

I'll do some testing and put out an update soon.

**Comment by boocs** [comment]
Should be fixed in latest release. Let me know!

**Comment by vladipus** [comment]
Great! Thanks. Will be testing now.

**Comment by vladipus** [comment]
Works alright! Closing the isssue.
