### ISSUE TITLE
error when launching: The following argument was not expected: /c

### ISSUE THREAD

**Issue by vladipus** [boocs/ue4-intellisense-fixes#33]
Seems like the recent versions of VSCode have a problem: https://forums.unrealengine.com/t/vscode-error-when-launching-the-following-argument-was-not-expected-c/1662628

The current solution is to specify "console": "integratedTerminal",

It would be cool if your nifty extension could address it automatically as well.

Thanks.

**Comment by boocs** [comment]
I used to have another fix for launch.json that was similar. Perhaps my extension is also fixing it to the wrong thing.

 I'll look into it!

**Comment by boocs** [comment]
I've checked and my previous launch.json fix doesn't affect this. It checks for the deprecated setting newExternalWindow and replaces it with externalTerminal.

For the particular problem you mentioned I'm not sure I should fix this as this is a VSCode bug not a deprecated setting. The VSCode bug will be fixed soon.

I guess I could create a separate extension quickly and do this though. I have some family stuff to do tonight so it might be delayed to tomorrow.

**Comment by boocs** [comment]
https://github.com/boocs/unreal-console-fix/

**Comment by vladipus** [comment]
I see this should be solved now.

Just passing by to still thank you for you time.
