### ISSUE TITLE
Hasn't been initialized properly

### ISSUE THREAD

**Issue by Ty-lerCox** [boocs/ue4-intellisense-fixes#6]
```
Extension "UE Intellisense Fixes" is now active!

Found Unreal Engine v5.0.0

** Error **: This fixable project hasn't been initialized properly and is invalid.
```

I am receiving the following error message when launching VSCode. Here are some of my configs:

c_cpp_properties.json:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "D:/Games/UE_5.0EA/**",
                "D:/Games/UE_5.0EA/Engine/Source/Runtime/**",
                "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/include",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.19041.0/shared"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files/LLVM/bin/clang-cl.exe",
            "cStandard": "gnu17",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-clang-x64"
        }
    ],
    "version": 4
}
```

Space.code-workspace
```
{
  "folders": [
    {
      "name": "Space",
      "path": "."
    },
    {
      "name": "UE5",
      "path": "D:\\Games\\UE_5.0EA"
    }
  ],
  "settings": {
    "intelliSenseMode": "windows-clang-x64",
    "C_Cpp.default.forcedInclude": [
      "C:/Users/user/projects/Space/Intermediate/Build/Win64/UnrealEditor/Development/Space/Definitions.Space.h"
    ]
  }
}
```

**Comment by boocs** [comment]
You shouldn't setup your own c_cpp_properties.json. Let UE set it up itself. If you need to add VSCode C++ settings you should set them in the global User config.

You'll need to reset your config so the default UE/VSCode c_cpp_properties.json is recreated. Right click on your project's *.uproject file and choose Generate Visual Studio Project Files.

If this doesn't work make sure UE5 is set to use VSCode. Open UE5 and go to Editor Preferences. Then go to Source Code and change the dropdown menu to Visual Studio Code.

**Comment by Ty-lerCox** [comment]
I have Visual Studio Code set as the IDE, but when I "Generate Visual Studio Project Files" it is using "Using Visual Studio 2019 14.29.30136 toolchain".

Do I need to uninstall VS 2019?

**Comment by Ty-lerCox** [comment]
```
Running D:/Games/UE_5.0EA/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.exe Development Win64 -Project="C:/Users/tycox/projects/Space/Space.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Win64 using Manual SDK 10.0.18362.0
Creating makefile for SpaceEditor (no existing makefile)
@progress push 5%
Parsing headers for SpaceEditor
  Running UnrealHeaderTool "C:\Users\tycox\projects\Space\Space.uproject" "C:\Users\tycox\projects\Space\Intermediate\Build\Win64\SpaceEditor\Development\SpaceEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\tycox\AppData\Local\UnrealBuildTool\Log_UHT.txt" -installed
Reflection code generated for SpaceEditor in 3.0228296 seconds
@progress pop
Building SpaceEditor...
Using Visual Studio 2019 14.29.30136 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
[Adaptive Build] Excluded from Space unity file: CockpitSystem.cpp, CollisionSystem.cpp, Interactable.cpp, MyPlayerState.cpp, Space.cpp, SpaceCharacter.cpp, SpaceGameMode.cpp, SpaceHUD.cpp, SpaceProjectile.cpp
Building 23 actions with 16 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 4%
  [1/23] Default.rc2
```

**Comment by boocs** [comment]
Were you able to figure out the problem?

**Comment by TomSol-hub** [comment]
Hey, I've got the same problem with UE4 ver 4.27.1

After much headache, I managed to get intellisence to work properly after editing the compileCommands_...json

It seems that there's a new format for the commands, where it puts the following path for the cl.exe
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\"

If I remove this section from the commands and save it, it's working again, but it'll be put in again if you select to Refresh your project.

**Comment by boocs** [comment]
@TomSol-hub 

What extension version are you running? That should've been fixed a few releases ago.

**Comment by TomSol-hub** [comment]
> What extension version are you running? That should've been fixed a few releases ago.

Hey, it says I'm on 2.1.0 - 
UE Intellisense Fixes
v2.1.0

**Comment by boocs** [comment]
@TomSol-hub 

I'm pretty sure if you upgrade to the latest it'll be fixed. I think it was 2.1.1 where I fixed the problem you're having.
