### ISSUE TITLE
Times out while searching for .uproject file

### ISSUE THREAD

**Issue by lukebrewerton** [boocs/ue4-intellisense-fixes#9]
I get the following error when VSCode starts up: ` [exthost] [info] Not activating extension 'boocs.ue4-intellisense-fixes': Timed out while searching for 'workspaceContains' pattern *.uproject`

I am using UE 4.27.2, VSCode 1.63.2, extension 2.2.0.

I have found this with a project converted from UE 4.26, and a newly created C++ project. The uproject file is definitely there and shows in the file explorer of VSCode

I have tried the Refresh VSCode project open and restarting VSCode but I still get the same error showing in the extension logs

**Comment by boocs** [comment]
That is very strange!

- What OS?
- What is the full name of the *.uproject file? (copy and paste exactly if you can)

**Comment by lukebrewerton** [comment]
Aah yes, I left out the OS. It's Windows 10.

I did install VSCode October 2021 a d jad the same issue, then installed August 2021 and it works fine so not sure if something changed in VSCode between those times

**Comment by boocs** [comment]
Has the August version been auto updated to the latest version and still working?

**Comment by lukebrewerton** [comment]
It has now, I put it off so I could get some bits done, but it still breaks even with the auto update

**Comment by boocs** [comment]
I've actually started getting this very rarely but can't consistently reproduce it. I don't know if putting a timer to delay the start would work or even be the best solution.

You can use the VSCode developer command Reload Window, after starting VSCode, to temporarily fix it(hopefully).

**Comment by boocs** [comment]
Might be easier than I thought.

Could you test the beta release to see if it fixes it?

https://github.com/boocs/ue4-intellisense-fixes/releases

**Comment by lukebrewerton** [comment]
The Beta version works! It's all happy again! Thank you!!

As a side note, the Docs search plugin is also effected by the same issue I just saw, not a big deal, but just making you aware

**Comment by boocs** [comment]
Made it non-beta with current release. Thanks for testing!

I'll release a docs search update soon.
